version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
  pre_build:
    commands:
      - cd ~
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - php composer.phar install
  build:
    commands:
      - echo Build started on `date`
      - composer create-project --prefer-dist laravel/laravel eb-laravel
  post_build:
    commands:
      - echo Build completed on `date`
