version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
  pre_build:
    commands:
      - cd ~
      - sudo curl -sS https://getcomposer.org/installer | sudo php
      - sudo mv composer.phar /usr/local/bin/composer
      - sudo ln -s /usr/local/bin/composer /usr/bin/composer
      - sudo composer install
      - php composer.phar install
  build:
    commands:
      - echo Build started on `date`
      - composer create-project --prefer-dist laravel/laravel eb-laravel
  post_build:
    commands:
      - echo Build completed on `date`
